name: data_browser_tox

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8]

    services:
      database:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: hunter2
        ports:
          - 3306:3306
        volumes:
          - type=tmpfs,destination=/var/lib/mysql

    env:
      DATABASE_URL: mysql://root:hunter2@127.0.0.1:3306/data_browser

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Test with tox
        run: tox
